name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: antonio-grosu
          template: "classic"
          base: "header, activity, community, repositories, metadata"
          config_timezone: "Europe/Bucharest"

          plugin_activity: "yes"
          plugin_activity_days: 30
          plugin_activity_filter: "pr"
          plugin_activity_visibility: "all"

          plugin_languages: "yes"
          plugin_languages_indepth: "yes"
          plugin_languages_ignored: "html, css"
          plugin_languages_details: "bytes-size, percentage"
          plugin_languages_limit: 8
          plugin_languages_sections: "most-used"  
          plugin_languages_analysis_timeout: 15

          plugin_habits: "yes"
          plugin_habits_facts: "yes"
          plugin_habits_charts: "yes"

          plugin_calendar: "yes"
          plugin_calendar_limit: 1
